# Generated by Django 4.0.5 on 2022-07-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
