# Generated by Django 4.0.5 on 2022-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Pinder\\pinderApp\\static\\pinderApp\x07ssets\\posteos'),
        ),
    ]
