# Generated by Django 4.0.5 on 2022-07-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imgPosteo',
        ),
    ]
