# Generated by Django 4.0.5 on 2022-07-14 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinderApp', '0007_rename_image_post_imgposteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('especie', models.CharField(choices=[('1', 'Perro'), ('2', 'Gato')], max_length=20)),
                ('sexo', models.CharField(choices=[('1', 'Macho'), ('2', 'Hembra')], max_length=20)),
                ('foto', models.CharField(max_length=9999999)),
                ('edad', models.PositiveIntegerField()),
                ('tamanio', models.CharField(choices=[('1', 'Grande'), ('2', 'Mediano'), ('3', 'Chico')], max_length=20)),
                ('vacunas_aplicadas', models.PositiveIntegerField()),
                ('castracion', models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=20)),
                ('desparasitado', models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=20)),
                ('discapacidad', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Prefiero no decirlo')], max_length=30)),
                ('imagen', models.ImageField(default='user.png', upload_to='')),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('localidad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=50)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('dias_homeoffice', models.PositiveIntegerField()),
                ('cantidad_hijos', models.PositiveIntegerField()),
                ('cantidad_mascotas', models.PositiveIntegerField()),
                ('especie_mascota', models.CharField(max_length=50)),
                ('espacio_abierto', models.CharField(choices=[('1', 'Patio o Parque'), ('2', 'Terraza o Balcon'), ('3', 'No poseo')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
