# Generated by Django 4.0.5 on 2022-07-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0008_animal_usuario_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.AddField(
            model_name='post',
            name='castracion',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], default='Elegir Opcion', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='desparasitado',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], default='Elegir Opcion', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='especie',
            field=models.CharField(choices=[('1', 'Perro'), ('2', 'Gato')], default='Elegir Opcion', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sexo',
            field=models.CharField(choices=[('1', 'Macho'), ('2', 'Hembra')], default='Elegir Opcion', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='tamanio',
            field=models.CharField(choices=[('1', 'Grande'), ('2', 'Mediano'), ('3', 'Chico')], default='Elegir Opcion', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='vacunas_aplicadas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
