# Generated by Django 4.0.5 on 2022-07-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0009_delete_animal_post_castracion_post_desparasitado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='last_name',
        ),
    ]
