# Generated by Django 4.0.5 on 2022-07-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0012_alter_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgPosteo',
            field=models.ImageField(upload_to='posteos'),
        ),
    ]
