# Generated by Django 4.0.5 on 2022-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0013_alter_post_imgposteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgPosteo',
            field=models.ImageField(null=True, upload_to='posteos'),
        ),
    ]
