# Generated by Django 4.0.5 on 2022-07-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0014_alter_post_imgposteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cantidad_hijos',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cantidad_mascotas',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carga_horaria',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dias_homeoffice',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
