# Generated by Django 4.0.5 on 2022-07-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0018_alter_usuario_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
