# Generated by Django 4.0.5 on 2022-07-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinderApp', '0021_alter_post_user'),
        ('pinderApp', '0026_alter_profile_image'),
    ]

    operations = [
    ]
